### ISSUE TITLE
Getting error loading cardSettings.txt

### ISSUE THREAD

**Issue by knightblaster** [Astr0-G/SplinterForge-Bot#1]
Hello, with the new beta released a couple of hours ago, I am getting "error loading cardSettings.txt" with this as cardSettings.txt:

bossId:summonersId,summonersId:monsterId,monsterId,..,monsterId:timeSleepInMinute(DONT remove this line)(bossIds are 14,15,16,17)(you can add as many monsterId as you want)
14:437,439:338,339,387,184,367,371,379:1

**Comment by astro-ge** [comment]
It works fine with [this newest hotfix](https://github.com/Astr0-G/SplinterForge-Bot/releases/tag/v0.2-beta.1), redownload the bot and retry please.

**Comment by knightblaster** [comment]
This fixed it, thanks!!
