### ISSUE TITLE
can I make timeSleepInMinute to 0, does that effect anything?

### ISSUE THREAD

**Issue by HoysEVA** [Astr0-G/SplinterForge-Bot#7]
I created a issue and got close, I am wondering if I put 0 will effect anything in the game?

**Comment by astro-ge** [comment]
As of right now, the bot use the driver to play the game, so there is no effect at all.

**Comment by HoysEVA** [comment]
> As of right now, the bot use the driver to play the game, so there is no effect at all.

okay I see
